### ISSUE TITLE
can i use function user.has_perm for checking permissions?

### ISSUE THREAD

**Issue by AlexByte** [vintasoftware/django-role-permissions#108]
For example `user.has_perm('sites.change_site', object)`

**Comment by AlexByte** [comment]
Why this function is not implemented as in django-guardian?

**Comment by filipeximenes** [comment]
Hi @AlexByte sorry for the delay. `django-role-permissions` does not handles permissions using the plain default django permissions framework. Role information is considered in the process that's why you can't use the `has_perm` method. 
I'm going to close this for now, LMK if you have other questions
